name: Publish
on: release

jobs:
  publish:
    runs-on: macos-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: "v2.x"

      - name: Install Ninja
        run: brew install ninja

      - name: Build Yoga
        run: deno task build-yoga

      - name: Build
        run: deno task build

      - name: Test
        run: deno task test

      - name: Publish
        run: deno publish
